<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace mj2\schema;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class Comment extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return Comment
     */
    public static function getRootAsComment(ByteBuffer $bb)
    {
        $obj = new Comment();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Comment
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getUserId()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    public function getContent()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startComment(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Comment
     */
    public static function createComment(FlatBufferBuilder $builder, $userId, $content)
    {
        $builder->startObject(2);
        self::addUserId($builder, $userId);
        self::addContent($builder, $content);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addUserId(FlatBufferBuilder $builder, $userId)
    {
        $builder->addOffsetX(0, $userId, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addContent(FlatBufferBuilder $builder, $content)
    {
        $builder->addOffsetX(1, $content, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endComment(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
