// automatically generated by the FlatBuffers compiler, do not modify

package mj2.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Comment extends Table {
  public static Comment getRootAsComment(ByteBuffer _bb) { return getRootAsComment(_bb, new Comment()); }
  public static Comment getRootAsComment(ByteBuffer _bb, Comment obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Comment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int rltTime() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String userId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String content() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createComment(FlatBufferBuilder builder,
      int rltTime,
      int userIdOffset,
      int contentOffset) {
    builder.startObject(3);
    Comment.addContent(builder, contentOffset);
    Comment.addUserId(builder, userIdOffset);
    Comment.addRltTime(builder, rltTime);
    return Comment.endComment(builder);
  }

  public static void startComment(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addRltTime(FlatBufferBuilder builder, int rltTime) { builder.addInt(0, rltTime, 0); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(1, userIdOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(2, contentOffset, 0); }
  public static int endComment(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

