// automatically generated by the FlatBuffers compiler, do not modify

package mj2.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SimulComments extends Table {
  public static SimulComments getRootAsSimulComments(ByteBuffer _bb) { return getRootAsSimulComments(_bb, new SimulComments()); }
  public static SimulComments getRootAsSimulComments(ByteBuffer _bb, SimulComments obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public SimulComments __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int rltTime() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public Comment comments(int j) { return comments(new Comment(), j); }
  public Comment comments(Comment obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int commentsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }

  public static int createSimulComments(FlatBufferBuilder builder,
      int rltTime,
      int commentsOffset) {
    builder.startObject(2);
    SimulComments.addComments(builder, commentsOffset);
    SimulComments.addRltTime(builder, rltTime);
    return SimulComments.endSimulComments(builder);
  }

  public static void startSimulComments(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addRltTime(FlatBufferBuilder builder, int rltTime) { builder.addInt(0, rltTime, 0); }
  public static void addComments(FlatBufferBuilder builder, int commentsOffset) { builder.addOffset(1, commentsOffset, 0); }
  public static int createCommentsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCommentsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endSimulComments(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

